// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRole = `-- name: AddRole :exec
INSERT INTO user_roles (user_id, role) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddRole(ctx context.Context, arg AddRoleParams) error {
	_, err := q.db.Exec(ctx, addRole, arg.UserID, arg.Role)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, phone, password_hash, full_name)
VALUES (NULLIF($1,'')::citext, NULLIF($2,''), $3, $4)
RETURNING id
`

type CreateUserParams struct {
	Column1      interface{} `json:"column_1"`
	Column2      interface{} `json:"column_2"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Column1,
		arg.Column2,
		arg.PasswordHash,
		arg.FullName,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByContact = `-- name: GetUserByContact :one
SELECT id, password_hash, is_active
FROM users
WHERE is_active AND (email = LOWER($1)::citext OR phone = $1)
LIMIT 1
`

type GetUserByContactRow struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) GetUserByContact(ctx context.Context, lower string) (GetUserByContactRow, error) {
	row := q.db.QueryRow(ctx, getUserByContact, lower)
	var i GetUserByContactRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.IsActive)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT role FROM user_roles WHERE user_id = $1
`

func (q *Queries) ListRoles(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
