// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: catalog.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (slug, name, short_desc, description, category_id, status, meta_title, meta_description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateProductParams struct {
	Slug            string      `json:"slug"`
	Name            string      `json:"name"`
	ShortDesc       string      `json:"short_desc"`
	Description     string      `json:"description"`
	CategoryID      pgtype.UUID `json:"category_id"`
	Status          string      `json:"status"`
	MetaTitle       string      `json:"meta_title"`
	MetaDescription string      `json:"meta_description"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Slug,
		arg.Name,
		arg.ShortDesc,
		arg.Description,
		arg.CategoryID,
		arg.Status,
		arg.MetaTitle,
		arg.MetaDescription,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO product_variants (product_id, sku, name, price_vnd)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateVariantParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Sku       string      `json:"sku"`
	Name      string      `json:"name"`
	PriceVnd  int64       `json:"price_vnd"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.ProductID,
		arg.Sku,
		arg.Name,
		arg.PriceVnd,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, slug, name, short_desc, description, meta_title, meta_description
FROM products
WHERE slug = $1 AND status = 'active'
`

type GetProductBySlugRow struct {
	ID              pgtype.UUID `json:"id"`
	Slug            string      `json:"slug"`
	Name            string      `json:"name"`
	ShortDesc       string      `json:"short_desc"`
	Description     string      `json:"description"`
	MetaTitle       string      `json:"meta_title"`
	MetaDescription string      `json:"meta_description"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ShortDesc,
		&i.Description,
		&i.MetaTitle,
		&i.MetaDescription,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT p.id, p.slug, p.name, p.short_desc, p.meta_title, p.meta_description,
       COALESCE(MIN(pv.price_vnd), 0)::bigint AS min_price_vnd
FROM products p
LEFT JOIN product_variants pv ON pv.product_id = p.id AND pv.is_active
WHERE p.status = 'active'
GROUP BY p.id
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListActiveProductsRow struct {
	ID              pgtype.UUID `json:"id"`
	Slug            string      `json:"slug"`
	Name            string      `json:"name"`
	ShortDesc       string      `json:"short_desc"`
	MetaTitle       string      `json:"meta_title"`
	MetaDescription string      `json:"meta_description"`
	MinPriceVnd     int64       `json:"min_price_vnd"`
}

func (q *Queries) ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]ListActiveProductsRow, error) {
	rows, err := q.db.Query(ctx, listActiveProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProductsRow
	for rows.Next() {
		var i ListActiveProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ShortDesc,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.MinPriceVnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProduct = `-- name: ListVariantsByProduct :many
SELECT id, sku, name, price_vnd
FROM product_variants
WHERE product_id = $1 AND is_active
ORDER BY price_vnd ASC
`

type ListVariantsByProductRow struct {
	ID       pgtype.UUID `json:"id"`
	Sku      string      `json:"sku"`
	Name     string      `json:"name"`
	PriceVnd int64       `json:"price_vnd"`
}

func (q *Queries) ListVariantsByProduct(ctx context.Context, productID pgtype.UUID) ([]ListVariantsByProductRow, error) {
	rows, err := q.db.Query(ctx, listVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVariantsByProductRow
	for rows.Next() {
		var i ListVariantsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.PriceVnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
