// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AffiliateAttribution struct {
	ID          int64              `json:"id"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	AffiliateID pgtype.UUID        `json:"affiliate_id"`
	RefCode     string             `json:"ref_code"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AffiliateClick struct {
	ID          int64              `json:"id"`
	RefCode     string             `json:"ref_code"`
	LandingPath string             `json:"landing_path"`
	VisitorID   string             `json:"visitor_id"`
	Ip          *netip.Addr        `json:"ip"`
	UserAgent   string             `json:"user_agent"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AffiliateProfile struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RefCode   string             `json:"ref_code"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID         int64              `json:"id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	ActorRole  string             `json:"actor_role"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   string             `json:"entity_id"`
	Data       []byte             `json:"data"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CommunityDistribution struct {
	ID         int64              `json:"id"`
	PeriodID   pgtype.UUID        `json:"period_id"`
	CustomerID pgtype.UUID        `json:"customer_id"`
	SalesVnd   int64              `json:"sales_vnd"`
	Points     int64              `json:"points"`
	JournalID  pgtype.UUID        `json:"journal_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CommunityPeriod struct {
	ID             pgtype.UUID        `json:"id"`
	PeriodKey      string             `json:"period_key"`
	PoolVnd        int64              `json:"pool_vnd"`
	DistributedVnd int64              `json:"distributed_vnd"`
	LeftoverVnd    int64              `json:"leftover_vnd"`
	Status         string             `json:"status"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Hub struct {
	ID                    pgtype.UUID        `json:"id"`
	OwnerUserID           pgtype.UUID        `json:"owner_user_id"`
	RegionCode            string             `json:"region_code"`
	Level                 int32              `json:"level"`
	Status                string             `json:"status"`
	CumulativePurchaseVnd int64              `json:"cumulative_purchase_vnd"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type HubInventory struct {
	HubID     pgtype.UUID        `json:"hub_id"`
	VariantID pgtype.UUID        `json:"variant_id"`
	Qty       int32              `json:"qty"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type HubPurchase struct {
	ID        pgtype.UUID        `json:"id"`
	HubID     pgtype.UUID        `json:"hub_id"`
	AmountVnd int64              `json:"amount_vnd"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LedgerEntry struct {
	ID        int64              `json:"id"`
	JournalID pgtype.UUID        `json:"journal_id"`
	WalletID  int64              `json:"wallet_id"`
	Direction string             `json:"direction"`
	Amount    int64              `json:"amount"`
	RefType   string             `json:"ref_type"`
	RefID     string             `json:"ref_id"`
	Memo      string             `json:"memo"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	AffiliateID pgtype.UUID        `json:"affiliate_id"`
	HubID       pgtype.UUID        `json:"hub_id"`
	RegionCode  string             `json:"region_code"`
	Status      string             `json:"status"`
	SubtotalVnd int64              `json:"subtotal_vnd"`
	ShippingVnd int64              `json:"shipping_vnd"`
	TotalVnd    int64              `json:"total_vnd"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type OrderAllocation struct {
	OrderID           pgtype.UUID        `json:"order_id"`
	TotalVnd          int64              `json:"total_vnd"`
	AffiliateVnd      int64              `json:"affiliate_vnd"`
	HubVnd            int64              `json:"hub_vnd"`
	CommunityVnd      int64              `json:"community_vnd"`
	ShareholderVnd    int64              `json:"shareholder_vnd"`
	CompanyVnd        int64              `json:"company_vnd"`
	JournalID         pgtype.UUID        `json:"journal_id"`
	AllocatedAt       pgtype.Timestamptz `json:"allocated_at"`
	ReversedAt        pgtype.Timestamptz `json:"reversed_at"`
	ReversalJournalID pgtype.UUID        `json:"reversal_journal_id"`
}

type OrderItem struct {
	ID           pgtype.UUID `json:"id"`
	OrderID      pgtype.UUID `json:"order_id"`
	VariantID    pgtype.UUID `json:"variant_id"`
	ProductName  string      `json:"product_name"`
	UnitPriceVnd int64       `json:"unit_price_vnd"`
	Qty          int32       `json:"qty"`
	LineTotalVnd int64       `json:"line_total_vnd"`
}

type OtpCode struct {
	ID         pgtype.UUID        `json:"id"`
	Identifier string             `json:"identifier"`
	CodeHash   string             `json:"code_hash"`
	Purpose    string             `json:"purpose"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID         pgtype.UUID        `json:"id"`
	OrderID    pgtype.UUID        `json:"order_id"`
	Provider   string             `json:"provider"`
	PaymentRef string             `json:"payment_ref"`
	AmountVnd  int64              `json:"amount_vnd"`
	Status     string             `json:"status"`
	Raw        []byte             `json:"raw"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID              pgtype.UUID        `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	ShortDesc       string             `json:"short_desc"`
	Description     string             `json:"description"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	Status          string             `json:"status"`
	Images          []byte             `json:"images"`
	MetaTitle       string             `json:"meta_title"`
	MetaDescription string             `json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ProductVariant struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Sku       string             `json:"sku"`
	Name      string             `json:"name"`
	PriceVnd  int64              `json:"price_vnd"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Region struct {
	Code       string  `json:"code"`
	Name       string  `json:"name"`
	ParentCode *string `json:"parent_code"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        *string            `json:"email"`
	Phone        *string            `json:"phone"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

type Wallet struct {
	ID        int64              `json:"id"`
	Kind      string             `json:"kind"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Withdrawal struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	AmountVnd        int64              `json:"amount_vnd"`
	Status           string             `json:"status"`
	BankAccount      string             `json:"bank_account"`
	BankName         string             `json:"bank_name"`
	HoldJournalID    pgtype.UUID        `json:"hold_journal_id"`
	ReleaseJournalID pgtype.UUID        `json:"release_journal_id"`
	PayoutJournalID  pgtype.UUID        `json:"payout_journal_id"`
	RequestedAt      pgtype.Timestamptz `json:"requested_at"`
	DecidedAt        pgtype.Timestamptz `json:"decided_at"`
	Note             string             `json:"note"`
}
