// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orders.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrder = `-- name: GetOrder :one
SELECT id, code, customer_id, affiliate_id, hub_id, region_code, status,
       subtotal_vnd, total_vnd, completed_at
FROM orders
WHERE id = $1
`

type GetOrderRow struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	AffiliateID pgtype.UUID        `json:"affiliate_id"`
	HubID       pgtype.UUID        `json:"hub_id"`
	RegionCode  string             `json:"region_code"`
	Status      string             `json:"status"`
	SubtotalVnd int64              `json:"subtotal_vnd"`
	TotalVnd    int64              `json:"total_vnd"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i GetOrderRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CustomerID,
		&i.AffiliateID,
		&i.HubID,
		&i.RegionCode,
		&i.Status,
		&i.SubtotalVnd,
		&i.TotalVnd,
		&i.CompletedAt,
	)
	return i, err
}

const getOrderAllocation = `-- name: GetOrderAllocation :one
SELECT order_id, total_vnd, affiliate_vnd, hub_vnd, community_vnd, shareholder_vnd, company_vnd,
       journal_id, allocated_at, reversed_at
FROM order_allocations
WHERE order_id = $1
`

type GetOrderAllocationRow struct {
	OrderID        pgtype.UUID        `json:"order_id"`
	TotalVnd       int64              `json:"total_vnd"`
	AffiliateVnd   int64              `json:"affiliate_vnd"`
	HubVnd         int64              `json:"hub_vnd"`
	CommunityVnd   int64              `json:"community_vnd"`
	ShareholderVnd int64              `json:"shareholder_vnd"`
	CompanyVnd     int64              `json:"company_vnd"`
	JournalID      pgtype.UUID        `json:"journal_id"`
	AllocatedAt    pgtype.Timestamptz `json:"allocated_at"`
	ReversedAt     pgtype.Timestamptz `json:"reversed_at"`
}

func (q *Queries) GetOrderAllocation(ctx context.Context, orderID pgtype.UUID) (GetOrderAllocationRow, error) {
	row := q.db.QueryRow(ctx, getOrderAllocation, orderID)
	var i GetOrderAllocationRow
	err := row.Scan(
		&i.OrderID,
		&i.TotalVnd,
		&i.AffiliateVnd,
		&i.HubVnd,
		&i.CommunityVnd,
		&i.ShareholderVnd,
		&i.CompanyVnd,
		&i.JournalID,
		&i.AllocatedAt,
		&i.ReversedAt,
	)
	return i, err
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT id, code, status, total_vnd, created_at
FROM orders
WHERE customer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByCustomerParams struct {
	CustomerID pgtype.UUID `json:"customer_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListOrdersByCustomerRow struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Status    string             `json:"status"`
	TotalVnd  int64              `json:"total_vnd"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOrdersByCustomer(ctx context.Context, arg ListOrdersByCustomerParams) ([]ListOrdersByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomer, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByCustomerRow
	for rows.Next() {
		var i ListOrdersByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Status,
			&i.TotalVnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
