// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRole(ctx context.Context, arg AddRoleParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) (pgtype.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error)
	CreateVariant(ctx context.Context, arg CreateVariantParams) (pgtype.UUID, error)
	GetOrder(ctx context.Context, id pgtype.UUID) (GetOrderRow, error)
	GetOrderAllocation(ctx context.Context, orderID pgtype.UUID) (GetOrderAllocationRow, error)
	GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error)
	GetUserByContact(ctx context.Context, lower string) (GetUserByContactRow, error)
	ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]ListActiveProductsRow, error)
	ListOrdersByCustomer(ctx context.Context, arg ListOrdersByCustomerParams) ([]ListOrdersByCustomerRow, error)
	ListRoles(ctx context.Context, userID pgtype.UUID) ([]string, error)
	ListVariantsByProduct(ctx context.Context, productID pgtype.UUID) ([]ListVariantsByProductRow, error)
}

var _ Querier = (*Queries)(nil)
