ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_hub_fk;
DROP TABLE IF EXISTS hub_purchases CASCADE;
DROP TABLE IF EXISTS hub_inventory CASCADE;
DROP TABLE IF EXISTS hubs CASCADE;
DROP TABLE IF EXISTS regions CASCADE;
